[package]
name = "rusty-notes"
version = "0.1.0"
edition = "2021"
description = "A fast, keyboard-driven Markdown note editor with live preview and vault-wide search"
license = "MIT"

[dependencies]
eframe = { version = "0.36.2", default-features = false, features = ["wgpu", "wayland", "x11", "default_fonts", "accesskit", "persistence"] }
egui = "0.36.2"
egui_commonmark = { version = "0.25.0", features = ["svg"] }

walkdir = "2.5.0"
regex = "1.13.1"
aho-corasick = "1.1.5"
syntect = { version = "5.3.0", default-features = false, features = ["default-fancy"] }

serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
dirs = "7.0.0"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true

[target.'cfg(windows)'.dependencies]
rfd = { version = "0.17.2", default-features = false, features = ["common-controls-v6"] }
